Rules:
  - Dataset_Location:
      id: 1
      status: On
  - Article_Length:
      id: 2
      status: On
  - GDELT_Definition:
      id: 3
      status: Off
      definition: Off
  - Common_Words:
      id: 4
      status: Off
  - Named_Entities:
      id: 5
      status: Off
  - Sentiment:
      id: 6
      status: On
Data:
   - Raw_Data:
       path: D:\Graduate School\text-classifier\data\gdelt\India_Assault
       total_files: 100
   - Labeled:
       file: D:\Graduate School\text-classifier\data\GDELT_Labeled\assault_labeled.csv

